language: node_js
node_js:
  - node
install:
  - npm install
  - npm install -g codecov
script:
  - npm run test:unit -- --coverage && codecov
  - npm run test:integration
# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN
#   keep-history: true
#   on:
#     branch: master
